### PR TITLE
style:changed the favicon file

### LINKED ISSUE #27: Update the website favicon file
The website favicon would be better if it was the Umeme Upo Logo with a transparent background and not Vercel logo

### PR DESCRIPTION
**Pull request by HossamTuwano**
Changed the favicon file from the default Next logo to the 'Umeme Upo?' logo.

### CODE REVIEW

**Comment by fredygerman** [comment]
Amazing stuff @HossamTuwano 🔥 but I think it would be best if the white background on the favicon could be removed.

**Comment by fredygerman** [comment]
@makindajack please assist on this

**Comment by fredygerman** [comment]
Yes I just tagged them and they are working on providing the new .ico file.

**Comment by fredygerman** [comment]
The logo is being worked on by @makindajack on #28 pull request.

I am going to close this one and we will continue working on the favicon design on #28. 

Thank you @HossamTuwano for your contribution 🥳

**Review by fredygerman — COMMENTED** [review]
The favicon has been changed now we will work with @makindajack to update the favicon design.

**Comment by HossamTuwano** [comment]
Thanks Fredy.

**Pull request merged**
