### PR TITLE
✨ feat: fetching locations and display on dropdown

### PR DESCRIPTION
**Pull request by Era360**
- location changes automatically initiates that location's power status fetch
- also hard coded some locations since the DB doesn't have locations table

### CODE REVIEW

**Comment by fredygerman** [comment]
Great stuff @Era360 🔥.

Now let's fix the build errors, do some clean up and get the new lease up soon. 🦾

**Comment by Era360** [comment]
@fredygerman deployment preview seems to be working. I think you should merge this.

**Comment by fredygerman** [comment]
Finally closing this PR 😮‍💨, we wen't a bit ooff track and added a few other stings and got new bugs but it's done ✅.
Thanks @Era360 for the contributions. 🤝

**Comment by fredygerman** [comment]
> @fredygerman deployment preview seems to be working. I think you should merge this.

I just merged, it's working well on prod 🥳. 

But I have noticed sometimes fetching for status can take a while especially on first visit. It must be because I no longer fetch the status on server side and made some components client due to some errors but I will get back to making all initial data be called server side.

**Comment by Era360** [comment]
got it. 💪🏽

**Comment by fredygerman** [comment]
Btw what's your Twitter handle again, I'll tag you on the next update I post there.

Also go to sleep bruh 😂.

**Pull request merged**
